// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

// Declared by the compiler. Every context type below names these.
type __Cookies = {
  get(name: string): string | undefined;
  all(): Record<string, string>;
  set(name: string, value: string, options?: __CookieOptions): void;
  delete(name: string, options?: __CookieOptions): void;
  signed: {
    get(name: string): Promise<string | undefined>;
    all(): Promise<Record<string, string>>;
    set(name: string, value: string, options?: __CookieOptions): Promise<void>
  }
};
type __Shape<T> = {
  [K in keyof T]: T[K] extends never[] ? any[] : T[K]
};
type __CookieOptions = {
  path?: string;
  domain?: string;
  maxAge?: number;
  expires?: Date;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None'
};

// Declared by the app, in the file each was written in.
type Hop = {
  label: string;
  detail: string;
  ms: number;
  cache: CacheState;
  ok: boolean;
  note: string | null;
};
type CacheState = 'hit' | 'miss' | 'none';
type AtUri = {
  authority: string;
  collection: string | null;
  rkey: string | null;
  href: string;
  uri: string;
};
type Identity = {
  did: string;
  handle: string | null;
  verified: boolean;
  pds: string;
  doc: any;
};

/** Properties of `<trace-rail>`, from its <script properties> block. */
export type TraceRailProps = {
  hops: Hop[];
  ms: number;
};

/** The `ctx` argument of `root/_layout.html`'s loader. */
export type RootLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `root/_layout.html`. */
export type RootLayoutData = {
  path: string;
};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {};

/** Route params for `/at/:uri{.+}`. */
export type AtUriRestParams = { uri: string };

/** The `ctx` argument of `at-_uri_rest`'s <script server> loader. */
export type AtUriRestContext = {
  url: string;
  params: {
    uri: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `at-_uri_rest`'s <script server> block. */
export type AtUriRestData = __Shape<{
  at: AtUri;
  kind: string;
  identity: Identity;
  data: any;
  hops: Hop[];
  ms: any;
  error: null;
}> | __Shape<{
  at: null;
  kind: null;
  identity: null;
  data: null;
  hops: Hop[];
  ms: any;
  error: any;
}>;

declare global {
  interface HTMLElementTagNameMap {
    "trace-rail": HTMLElement;
  }
}
