// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

// Declared by the compiler. Every context type below names these.
type __Cookies = {
  get(name: string): string | undefined;
  all(): Record<string, string>;
  set(name: string, value: string, options?: __CookieOptions): void;
  delete(name: string, options?: __CookieOptions): void;
  signed: {
    get(name: string): Promise<string | undefined>;
    all(): Promise<Record<string, string>>;
    set(name: string, value: string, options?: __CookieOptions): Promise<void>
  }
};
type __Shape<T> = {
  [K in keyof T]: T[K] extends never[] ? any[] : T[K]
};
type __CookieOptions = {
  path?: string;
  domain?: string;
  maxAge?: number;
  expires?: Date;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None'
};

// Declared by the app, in the file each was written in.
type Field = {
  name: string;
  kind: string;
  text: string;
  href: string | null;
  depth: number;
  required: boolean;
  description: string | null;
  meta: Record<string, any>;
  items: string[];
};
type Backlink = {
  collection: string;
  path: string;
  count: number;
  href: string;
};
type Row = {
  rkey: string;
  href: string;
  summary: string;
  when: string;
};
type Row_2 = Hop & {
  count: number;
};
type Hop = {
  label: string;
  detail: string;
  ms: number;
  cache: CacheState;
  ok: boolean;
  note: string | null;
};
type CacheState = 'hit' | 'miss' | 'none';
type Identity = {
  did: string;
  handle: string | null;
  verified: boolean;
  pds: string;
  doc: any;
};
type Lexicon = {
  nsid: string;
  did: string;
  uri: string;
  cid: string;
  schema: any;
};
type AtUri = {
  authority: string;
  collection: string | null;
  rkey: string | null;
  href: string;
  uri: string;
};

/** Properties of `<field-list>`, from its <script properties> block. */
export type FieldListProps = {
  fields: Field[];
};

/** Properties of `<link-list>`, from its <script properties> block. */
export type LinkListProps = {
  links: Backlink[];
};

/** Properties of `<record-card>`, from its <script properties> block. */
export type RecordCardProps = {
  uri: string;
  cid: string;
  collection: string;
  schema: boolean;
};

/** Properties of `<record-row>`, from its <script properties> block. */
export type RecordRowProps = {
  rows: Row[];
};

/** Properties of `<trace-rail>`, from its <script properties> block. */
export type TraceRailProps = {
  hops: Row_2[];
  ms: number;
  requests: number;
};

/** The `ctx` argument of `root/_layout.html`'s loader. */
export type RootLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `root/_layout.html`. */
export type RootLayoutData = {
  path: string;
  bare: boolean;
};

/** The `ctx` argument of `about`'s <script server> loader. */
export type AboutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    bare: boolean;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `about`'s <script server> block. */
export type AboutData = {
  server: string;
  allow: string;
  element: string;
  client: string;
};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    bare: boolean;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {};

/** Route params for `/did/:id`. */
export type DidIdParams = { id: string };

/** The `ctx` argument of `did-_id`'s <script server> loader. */
export type DidIdContext = {
  url: string;
  params: {
    id: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    bare: boolean;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `did-_id`'s <script server> block. */
export type DidIdData = __Shape<{
  identity: Identity;
  services: any;
  keys: any;
  log: any;
  links: Backlink[];
  hops: Row_2[];
  requests: number;
  ms: any;
  error: null;
}> | __Shape<{
  identity: null;
  services: never[];
  keys: never[];
  log: never[];
  links: never[];
  hops: Row_2[];
  requests: number;
  ms: any;
  error: any;
}>;

/** Route params for `/lexicon/:nsid`. */
export type LexiconNsidParams = { nsid: string };

/** The `ctx` argument of `lexicon-_nsid`'s <script server> loader. */
export type LexiconNsidContext = {
  url: string;
  params: {
    nsid: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    bare: boolean;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `lexicon-_nsid`'s <script server> block. */
export type LexiconNsidData = __Shape<{
  nsid: string;
  hops: Row_2[];
  requests: number;
  ms: any;
  error: null;
  searched: string[];
  lexicon: null;
  defs: never[];
  properties: never[];
  needs: never[];
  users: never[];
  example: null;
}> | __Shape<{
  nsid: string;
  lexicon: Lexicon;
  defs: {
    name: string;
    def: any;
  }[];
  properties: {
    name: string;
    required: boolean;
    type: any;
    format: any;
    description: any;
    limits: string;
    ref: any;
  }[];
  needs: string[];
  users: string[];
  example: {
    uri: any;
    href: string;
    fields: Field[];
  } | null;
  hops: Row_2[];
  requests: number;
  ms: any;
  error: null;
  searched: never[];
}> | __Shape<{
  nsid: string;
  hops: Row_2[];
  requests: number;
  ms: any;
  error: any;
  lexicon: null;
  defs: never[];
  properties: never[];
  needs: never[];
  searched: never[];
  users: never[];
  example: null;
}>;

/** Route params for `/at/:uri{.+}`. */
export type AtUriRestParams = { uri: string };

/** The `ctx` argument of `at-_uri_rest`'s <script server> loader. */
export type AtUriRestContext = {
  url: string;
  params: {
    uri: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    bare: boolean;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `at-_uri_rest`'s <script server> block. */
export type AtUriRestData = __Shape<{
  at: AtUri;
  kind: string;
  identity: Identity;
  hops: Row_2[];
  requests: number;
  ms: any;
  error: null;
  raw: any;
  collections: any;
  fields: never[];
  rows: never[];
  schema: boolean;
  cursor: null;
  links: never[];
}> | __Shape<{
  at: AtUri;
  kind: string;
  identity: Identity;
  hops: Row_2[];
  requests: number;
  ms: any;
  error: null;
  raw: any;
  fields: Field[];
  schema: boolean;
  links: Backlink[];
  rows: never[];
  collections: never[];
  cursor: null;
}> | __Shape<{
  at: AtUri;
  kind: string;
  identity: Identity;
  hops: Row_2[];
  requests: number;
  ms: any;
  error: null;
  raw: any;
  schema: boolean;
  cursor: any;
  rows: any;
  fields: never[];
  collections: never[];
  links: never[];
}> | __Shape<{
  hops: Row_2[];
  requests: number;
  ms: any;
  error: any;
  at: null;
  kind: null;
  identity: null;
  raw: null;
  fields: never[];
  rows: never[];
  collections: never[];
  schema: boolean;
  cursor: null;
  links: never[];
}>;

/** Route params for `/embed/:uri{.+}`. */
export type EmbedUriRestParams = { uri: string };

/** The `ctx` argument of `embed-_uri_rest`'s <script server> loader. */
export type EmbedUriRestContext = {
  url: string;
  params: {
    uri: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    bare: boolean;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `embed-_uri_rest`'s <script server> block. */
export type EmbedUriRestData = __Shape<{
  gone: null;
  raw: any;
  schema: boolean;
  uri: any;
  fields: Field[];
  at: AtUri;
  identity: Identity;
}> | __Shape<{
  uri: string;
  gone: any;
  at: null;
  identity: null;
  raw: null;
  fields: never[];
  schema: boolean;
}>;

declare global {
  interface HTMLElementTagNameMap {
    "field-list": HTMLElement;
    "link-list": HTMLElement;
    "record-card": HTMLElement;
    "record-row": HTMLElement;
    "trace-rail": HTMLElement;
  }
}
