// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

/** Properties of `<card-list>`, from its <script properties> block. */
export type CardListProps = {
  heading: string;
  people: Person[];
};

/** Properties of `<state-probe>`, from its <script properties> block. */
export type StateProbeProps = {
  label: string;
  open: boolean;
  rows: {
    id: number;
    label: string;
    flagged: boolean;
  }[];
};

/** Properties of `<tag-picker>`, from its <script properties> block. */
export type TagPickerProps = {
  value: string;
  options: string[];
  disabled: boolean;
};

/** Internal state of `<tag-picker>`, from its <script state> block. */
export type TagPickerState = {
  open: boolean;
};

/** Members of `<tag-picker>`, from its `export const prototype`. */
export type TagPickerMembers = {
  readonly chosen: any;
  toggle(tag: any): void;
};

/** Properties of `<user-card>`, from its <script properties> block. */
export type UserCardProps = {
  name: string;
  role: string;
  tags: string[];
  compact: boolean;
  since: Date;
};

/** Internal state of `<user-card>`, from its <script state> block. */
export type UserCardState = {
  clicks: number;
};

/** Members of `<user-card>`, from its `export const prototype`. */
export type UserCardMembers = {
  readonly tagCount: number;
  toggle(): boolean;
  addTag(tag: any): void;
  updated(): void;
};

/** Properties of `<data-table>`, from its <script properties> block. */
export type DataTableProps = {
  caption: string;
  columns: string[];
  rows: string[][];
  emptyLabel: string;
};

/** Properties of `<live-count>`, from its <script properties> block. */
export type LiveCountProps = {
  count: number;
  label: string;
};

/** Members of `<live-count>`, from its `export const prototype`. */
export type LiveCountMembers = {
  add(n?: number): void;
};

/** Properties of `<site-note>`, from its <script properties> block. */
export type SiteNoteProps = {
  tone: string;
};

/** Members of `<site-note>`, from its `export const prototype`. */
export type SiteNoteMembers = {
  dismiss(): void;
  readonly dismissed: boolean;
};

/** Properties of `<tally-box>`, from its <script properties> block. */
export type TallyBoxProps = {
  label: string;
};

/** Internal state of `<tally-box>`, from its <script state> block. */
export type TallyBoxState = {
  n: number;
};

/** Members of `<tally-box>`, from its `export const prototype`. */
export type TallyBoxMembers = {
  bump(by?: number): void;
};

/** The `ctx` argument of `root/_layout.html`'s loader. */
export type RootLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `root/_layout.html`. */
export type RootLayoutData = {
  path: string;
  links: {
    href: string;
    label: string;
  }[];
};

/** The `ctx` argument of `people/_layout.html`'s loader. */
export type PeopleLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    links: {
      href: string;
      label: string;
    }[];
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `people/_layout.html`. */
export type PeopleLayoutData = {
  total: number;
};

/** The `ctx` argument of `check`'s <script server> loader. */
export type CheckContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    links: {
      href: string;
      label: string;
    }[];
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `check`'s <script server> block. */
export type CheckData = {
  people: {
    name: string;
    role: string;
    tags: string[];
    joined: Date;
  }[];
};

/** The `ctx` argument of `notes`'s <script server> loader. */
export type NotesContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    links: {
      href: string;
      label: string;
    }[];
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `notes`'s <script server> block. */
export type NotesData = {
  notes: {
    id: number;
    text: string;
    tags: string[];
  }[];
  mine: number;
  error: string | null;
  added: string | null;
};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    links: {
      href: string;
      label: string;
    }[];
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {
  heading: string;
  note: string;
  trusted: string;
  people: {
    slug: string;
    name: string;
    role: string;
    tags: string[];
    since: number;
    joined: Date;
    note: string;
  }[];
  table: {
    columns: string[];
    rows: string[][];
  };
  query: string | null;
  matches: {
    slug: string;
    name: string;
    role: string;
    tags: string[];
    since: number;
    joined: Date;
    note: string;
  }[];
  matchRows: string[][];
};

/** Route params for `/people/:name`. */
export type PeopleNameParams = { name: string };

/** The `ctx` argument of `people-_name`'s <script server> loader. */
export type PeopleNameContext = {
  url: string;
  params: {
    name: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: Omit<{
    path: string;
    links: {
      href: string;
      label: string;
    }[];
  }, keyof {
    total: number;
  }> & {
    total: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `people-_name`'s <script server> block. */
export type PeopleNameData = {
  person: {
    slug: string;
    name: string;
    role: string;
    tags: string[];
    since: number;
    joined: Date;
    note: string;
  } | null;
  slug: string;
  others: {
    slug: string;
    name: string;
    role: string;
    tags: string[];
    since: number;
    joined: Date;
    note: string;
  }[];
  rank: string;
};

/** Route params for `/docs/:path{.+}`. */
export type DocsPathRestParams = { path: string };

/** The `ctx` argument of `docs-_path_rest`'s <script server> loader. */
export type DocsPathRestContext = {
  url: string;
  params: {
    path: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    links: {
      href: string;
      label: string;
    }[];
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `docs-_path_rest`'s <script server> block. */
export type DocsPathRestData = {
  path: string;
  crumbs: string[];
};

/** The `ctx` argument of `404`'s <script server> loader. */
export type _404Context = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    path: string;
    links: {
      href: string;
      label: string;
    }[];
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `404`'s <script server> block. */
export type _404Data = {};

declare global {
  interface HTMLElementTagNameMap {
    "card-list": HTMLElement;
    "state-probe": HTMLElement;
    "tag-picker": HTMLElement & TagPickerProps & TagPickerState & TagPickerMembers;
    "user-card": HTMLElement & UserCardProps & UserCardState & UserCardMembers;
    "data-table": HTMLElement;
    "live-count": HTMLElement & LiveCountProps & LiveCountMembers;
    "site-note": HTMLElement & SiteNoteProps & SiteNoteMembers;
    "tally-box": HTMLElement & TallyBoxProps & TallyBoxState & TallyBoxMembers;
  }
}
