// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

// Declared by the compiler. Every context type below names these.
type __Cookies = {
  get(name: string): string | undefined;
  all(): Record<string, string>;
  set(name: string, value: string, options?: __CookieOptions): void;
  delete(name: string, options?: __CookieOptions): void;
  signed: {
    get(name: string): Promise<string | undefined>;
    all(): Promise<Record<string, string>>;
    set(name: string, value: string, options?: __CookieOptions): Promise<void>
  }
};
type __CookieOptions = {
  path?: string;
  domain?: string;
  maxAge?: number;
  expires?: Date;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None'
};

/** The `ctx` argument of `root/_layout.html`'s loader. */
export type RootLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `root/_layout.html`. */
export type RootLayoutData = {
  user: {
    id: number;
    email: string;
    name: string;
    salt: string;
    hash: string;
  } | null;
};

/** The `ctx` argument of `admin/_layout.html`'s loader. */
export type AdminLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    } | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `admin/_layout.html`. */
export type AdminLayoutData = {
  user: {
    id: number;
    email: string;
    name: string;
    salt: string;
    hash: string;
  };
};

/** The `ctx` argument of `admin-settings`'s <script server> loader. */
export type AdminSettingsContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: Omit<{
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    } | null;
  }, keyof {
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    };
  }> & {
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    };
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `admin-settings`'s <script server> block. */
export type AdminSettingsData = {
  name: string;
};

/** The `ctx` argument of `admin-index`'s <script server> loader. */
export type AdminIndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: Omit<{
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    } | null;
  }, keyof {
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    };
  }> & {
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    };
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `admin-index`'s <script server> block. */
export type AdminIndexData = {};

/** The `ctx` argument of `login`'s <script server> loader. */
export type LoginContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    } | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `login`'s <script server> block. */
export type LoginData = {
  error: string | null;
  next: string;
};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    } | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {
  user: {
    id: number;
    email: string;
    name: string;
    salt: string;
    hash: string;
  } | null;
};

/** The `ctx` argument of `404`'s <script server> loader. */
export type _404Context = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    user: {
      id: number;
      email: string;
      name: string;
      salt: string;
      hash: string;
    } | null;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `404`'s <script server> block. */
export type _404Data = {};
