// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

/** The `ctx` argument of `root/_layout.html`'s loader. */
export type RootLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `root/_layout.html`. */
export type RootLayoutData = {};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {
  show: string | null;
  items: {
    id: number;
    text: string;
    done: boolean;
  }[];
  left: number;
  hasDone: boolean;
  any: boolean;
  allDone: boolean;
  editing: number;
};

/** The `ctx` argument of `404`'s <script server> loader. */
export type _404Context = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `404`'s <script server> block. */
export type _404Data = {};
