// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

/** The `ctx` argument of `elsewhere`'s <script server> loader. */
export type ElsewhereContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `elsewhere`'s <script server> block. */
export type ElsewhereData = {};

/** The `ctx` argument of `notes`'s <script server> loader. */
export type NotesContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `notes`'s <script server> block. */
export type NotesData = {
  notes: {
    id: number;
    text: string;
  }[];
};

/** The `ctx` argument of `summary`'s <script server> loader. */
export type SummaryContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `summary`'s <script server> block. */
export type SummaryData = {};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {
  price: string;
};

/** The `ctx` argument of `404`'s <script server> loader. */
export type _404Context = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `404`'s <script server> block. */
export type _404Data = {};
