// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

// Declared by the compiler. Every context type below names these.
type __Cookies = {
  get(name: string): string | undefined;
  all(): Record<string, string>;
  set(name: string, value: string, options?: __CookieOptions): void;
  delete(name: string, options?: __CookieOptions): void;
  signed: {
    get(name: string): Promise<string | undefined>;
    all(): Promise<Record<string, string>>;
    set(name: string, value: string, options?: __CookieOptions): Promise<void>
  }
};
type __Shape<T> = {
  [K in keyof T]: T[K] extends never[] ? any[] : T[K]
};
type __CookieOptions = {
  path?: string;
  domain?: string;
  maxAge?: number;
  expires?: Date;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None'
};

// Declared by the app, in the file each was written in.
type State = {
  have: string[];
  seen: string[];
  seed: string;
};
type Room = {
  id: string;
  title: string;
  at: [number, number];
  prose: string[];
  unlit?: string[] | undefined;
  moods?: string[] | undefined;
  item?: {
    id: string;
    line: string;
    gone: string;
  } | undefined;
  exits: Record<string, Exit>;
  ending?: boolean | undefined;
};
type Exit = string | Door;
type Door = {
  room: string;
  requires: string;
  locked: string;
};
type Item = {
  id: string;
  name: string;
  note: string;
};

/** The `ctx` argument of `root/_layout.html`'s loader. */
export type RootLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `root/_layout.html`. */
export type RootLayoutData = {};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {};

/** Route params for `/dungeon/:room`. */
export type DungeonRoomParams = { room: string };

/** The `ctx` argument of `dungeon-_room`'s <script server> loader. */
export type DungeonRoomContext = {
  url: string;
  params: {
    room: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `dungeon-_room`'s <script server> block. */
export type DungeonRoomData = __Shape<{
  lines: never[];
  exits: never[];
  take: null;
  held: never[];
  carried: string;
  gone: null;
  map: never[];
  extent: {
    cols: number;
    rows: number;
  };
  panel: string;
  total: number;
  room: null;
  title: string;
  asked: string;
  state: State;
}> | __Shape<{
  room: Room;
  title: string;
  asked: string;
  state: {
    have: string[];
    seed: string;
    seen: string[];
  };
  lines: any;
  exits: {
    dir: any;
    arrow: any;
    locked: any;
    href: string | null;
    to: any;
  }[];
  take: {
    line: string;
    name: string;
    href: string;
  } | null;
  gone: string | null;
  held: Item[];
  map: {
    title: string;
    col: number;
    row: number;
    here: boolean;
  }[];
  extent: {
    cols: number;
    rows: number;
  };
  panel: string;
  total: number;
  carried: string;
}>;

/** The `ctx` argument of `404`'s <script server> loader. */
export type _404Context = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `404`'s <script server> block. */
export type _404Data = {};
