// Emits transclude-env.d.ts from what TypeScript made of each file.
//
// Everything here is a type *string* produced by tsc's own printer, so this file
// formats and names things and nothing else. Nothing infers.

export function emitTypes({ components = [], partials = [], layouts = [], pages = [] } = {}) {
  const out = [
    '// Generated by transclude. Do not edit. `npm run check` rewrites it.',
    '//',
    '// Every type here was produced by TypeScript from the file it describes.',
    '',
    'export {};',
    '',
  ];

  for (const { tag, type, members, state } of [...components, ...partials]) {
    out.push(`/** Properties of \`<${tag}>\`, from its <script properties> block. */`);
    out.push(`export type ${interfaceName(tag)}Props = ${pretty(type)};`);
    out.push('');
    if (state) {
      out.push(`/** Internal state of \`<${tag}>\`, from its <script state> block. */`);
      out.push(`export type ${interfaceName(tag)}State = ${pretty(state)};`);
      out.push('');
    }
    if (members) {
      out.push(`/** Members of \`<${tag}>\`, from its \`export const prototype\`. */`);
      out.push(`export type ${interfaceName(tag)}Members = ${pretty(members)};`);
      out.push('');
    }
  }

  for (const { id, type, context } of layouts) {
    const name = `${interfaceName(id)}Layout`;
    out.push(`/** The \`ctx\` argument of \`${id}/_layout.html\`'s loader. */`);
    out.push(`export type ${name}Context = ${pretty(context ?? 'unknown')};`);
    out.push('');
    out.push(`/** Data returned by \`${id}/_layout.html\`. */`);
    out.push(`export type ${name}Data = ${pretty(type)};`);
    out.push('');
  }

  for (const { id, type, context, params = [], pattern } of pages) {
    const name = interfaceName(id);

    if (params.length) {
      out.push(`/** Route params for \`${pattern}\`. */`);
      out.push(`export type ${name}Params = { ${params.map((p) => `${p}: string`).join('; ')} };`);
      out.push('');
    }
    out.push(`/** The \`ctx\` argument of \`${id}\`'s <script server> loader. */`);
    out.push(`export type ${name}Context = ${pretty(context ?? 'unknown')};`);
    out.push('');
    out.push(`/** Data returned by \`${id}\`'s <script server> block. */`);
    out.push(`export type ${name}Data = ${pretty(type)};`);
    out.push('');
  }

  if (components.length || partials.length) {
    out.push('declare global {');
    out.push('  interface HTMLElementTagNameMap {');
    // A partial is an undefined custom element, so it is an HTMLElement too.
    // querySelector should know about it even though nothing registers it.
    for (const { tag, upgrades, members, state } of [...components, ...partials]) {
      const name = interfaceName(tag);
      // Accessors exist only where something registers the element. Where
      // nothing does, the tag is still an HTMLElement, just a plain one.
      const parts = ['HTMLElement'];
      if (upgrades) parts.push(`${name}Props`);
      if (state) parts.push(`${name}State`);
      if (members) parts.push(`${name}Members`);
      out.push(`    ${JSON.stringify(tag)}: ${parts.join(' & ')};`);
    }
    out.push('  }');
    out.push('}');
    out.push('');
  }

  return out.join('\n');
}

/**
 * tsc prints a type on one line. Breaking it at top-level separators keeps a
 * generated file worth opening; anything it cannot parse is left alone.
 */
function pretty(type, indent = '') {
  if (!type || !type.includes('{')) return type;
  // tsc prints an empty object as `{}`; expanding it leaves a blank line.
  if (type.trim() === '{}') return '{}';

  let out = '';
  let depth = 0;
  let quote = null;

  for (let i = 0; i < type.length; i++) {
    const char = type[i];

    if (quote) {
      out += char;
      if (char === quote && type[i - 1] !== '\\') quote = null;
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      out += char;
      continue;
    }

    if (char === '{') {
      // `{}` stays on one line; expanding it leaves a blank body.
      const rest = type.slice(i + 1).replace(/^\s*/, '');
      if (rest.startsWith('}')) {
        out += '{}';
        i = type.indexOf('}', i + 1);
        continue;
      }
      depth++;
      out += `{\n${indent}${'  '.repeat(depth)}`;
      continue;
    }
    if (char === '}') {
      depth--;
      out = out.replace(/[ \t]+$/, '');
      out += `\n${indent}${'  '.repeat(depth)}}`;
      continue;
    }
    if (char === ';' && depth > 0) {
      const rest = type.slice(i + 1).replace(/^\s*/, '');
      out += rest.startsWith('}') ? ';' : `;\n${indent}${'  '.repeat(depth)}`;
      continue;
    }
    if (char === ' ' && out.endsWith('\n' + indent + '  '.repeat(depth))) continue;
    out += char;
  }
  return out;
}

/**
 * `user-card` -> `UserCard`, `people-_name` -> `PeopleName`, `404` -> `_404`.
 *
 * The result has to be a valid TypeScript identifier, and a route named for a
 * status code starts with a digit, which is a syntax error, not a style one.
 */
export function interfaceName(name) {
  const camel = String(name)
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');

  if (!camel) return 'Anonymous';
  return /^[0-9]/.test(camel) ? `_${camel}` : camel;
}
