// Emits transclude-env.d.ts from what TypeScript made of each file.
//
// Everything here is a type *string* produced by tsc's own printer, so this file
// formats and names things and nothing else. Nothing infers.

import { ambientDeclarations } from './ambient.js';

/**
 * One element, as `src/typecheck.js` extracted it. Every field is a type
 * *string* that tsc's own printer produced.
 *
 * @typedef {object} ElementTypes
 * @property {string} tag
 * @property {string} type the props
 * @property {string} [state]
 * @property {string} [members] what `export const prototype` declared
 * @property {boolean} [upgrades] whether anything registers the element
 *
 * @typedef {object} RouteTypes
 * @property {string} id
 * @property {string} type what the loader returns
 * @property {string} [context] the `ctx` it is handed
 * @property {string[]} [params]
 * @property {string} [pattern]
 *
 * @param {{ components?: ElementTypes[], partials?: ElementTypes[],
 *   layouts?: RouteTypes[], pages?: RouteTypes[],
 *   types?: { name: string, type: string }[] }} [what] `partials` is the light
 *   elements: the key is the old name and is load-bearing until the callers
 *   change with it. `types` are the names the app declared that the strings
 *   below use.
 * @returns {string} the contents of transclude-env.d.ts
 */
export function emitTypes({
  components = [],
  partials = [],
  layouts = [],
  pages = [],
  types = [],
} = {}) {
  const out = [
    '// Generated by transclude. Do not edit. `npm run check` rewrites it.',
    '//',
    '// Every type here was produced by TypeScript from the file it describes.',
    '',
    'export {};',
    '',
  ];

  // Where the declarations go once it is known which are needed.
  const head = out.length;

  for (const { tag, type, members, state } of [...components, ...partials]) {
    out.push(`/** Properties of \`<${tag}>\`, from its <script element> block. */`);
    out.push(`export type ${interfaceName(tag)}Props = ${pretty(type)};`);
    out.push('');
    if (state) {
      out.push(`/** Internal state of \`<${tag}>\`, from its <script element> block. */`);
      out.push(`export type ${interfaceName(tag)}State = ${pretty(state)};`);
      out.push('');
    }
    if (members) {
      out.push(`/** Members of \`<${tag}>\`, from its \`export const prototype\`. */`);
      out.push(`export type ${interfaceName(tag)}Members = ${pretty(members)};`);
      out.push('');
    }
  }

  for (const { id, type, context } of layouts) {
    const name = `${interfaceName(id)}Layout`;
    out.push(`/** The \`ctx\` argument of \`${id}/_layout.html\`'s loader. */`);
    out.push(`export type ${name}Context = ${pretty(context ?? 'unknown')};`);
    out.push('');
    out.push(`/** Data returned by \`${id}/_layout.html\`. */`);
    out.push(`export type ${name}Data = ${pretty(type)};`);
    out.push('');
  }

  for (const { id, type, context, params = [], pattern } of pages) {
    const name = interfaceName(id);

    if (params.length) {
      out.push(`/** Route params for \`${pattern}\`. */`);
      out.push(`export type ${name}Params = { ${params.map((p) => `${p}: string`).join('; ')} };`);
      out.push('');
    }
    out.push(`/** The \`ctx\` argument of \`${id}\`'s <script server> loader. */`);
    out.push(`export type ${name}Context = ${pretty(context ?? 'unknown')};`);
    out.push('');
    out.push(`/** Data returned by \`${id}\`'s <script server> block. */`);
    out.push(`export type ${name}Data = ${pretty(type)};`);
    out.push('');
  }

  if (components.length || partials.length) {
    out.push('declare global {');
    out.push('  interface HTMLElementTagNameMap {');
    // A light element registers as a custom element too, so it is an HTMLElement.
    // querySelector should know about it even though nothing registers it.
    for (const { tag, upgrades, members, state } of [...components, ...partials]) {
      const name = interfaceName(tag);
      // Accessors exist only where something registers the element. Where
      // nothing does, the tag is still an HTMLElement, just a plain one.
      const parts = ['HTMLElement'];
      if (upgrades) parts.push(`${name}Props`);
      if (state) parts.push(`${name}State`);
      if (members) parts.push(`${name}Members`);
      out.push(`    ${JSON.stringify(tag)}: ${parts.join(' & ')};`);
    }
    out.push('  }');
    out.push('}');
    out.push('');
  }

  // Written last and put first. What has to be declared is whatever the types
  // above ended up naming, which is not known until they are all built.
  const body = out.slice(head).join('\n');
  const declared = [
    ...ambientDeclarations(body, (type) => pretty(type)),
    ...(types.length
      ? [
          '// Declared by the app, in the file each was written in.',
          ...types.map(({ name, type }) => `type ${name} = ${pretty(type)};`),
          '',
        ]
      : []),
  ];

  out.splice(head, 0, ...declared);
  return out.join('\n');
}

/**
 * tsc prints a type on one line. Breaking it at top-level separators keeps a
 * generated file worth opening; anything it cannot parse is left alone.
 */
function pretty(type, indent = '') {
  if (!type || !type.includes('{')) return type;
  // tsc prints an empty object as `{}`; expanding it leaves a blank line.
  if (type.trim() === '{}') return '{}';

  let out = '';
  let depth = 0;
  let quote = null;

  for (let i = 0; i < type.length; i++) {
    const char = type[i];

    if (quote) {
      out += char;
      if (char === quote && type[i - 1] !== '\\') quote = null;
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      out += char;
      continue;
    }

    if (char === '{') {
      // `{}` stays on one line; expanding it leaves a blank body.
      const rest = type.slice(i + 1).replace(/^\s*/, '');
      if (rest.startsWith('}')) {
        out += '{}';
        i = type.indexOf('}', i + 1);
        continue;
      }
      depth++;
      out += `{\n${indent}${'  '.repeat(depth)}`;
      continue;
    }
    if (char === '}') {
      depth--;
      out = out.replace(/[ \t]+$/, '');
      out += `\n${indent}${'  '.repeat(depth)}}`;
      continue;
    }
    if (char === ';' && depth > 0) {
      const rest = type.slice(i + 1).replace(/^\s*/, '');
      out += rest.startsWith('}') ? ';' : `;\n${indent}${'  '.repeat(depth)}`;
      continue;
    }
    if (char === ' ' && out.endsWith('\n' + indent + '  '.repeat(depth))) continue;
    out += char;
  }
  return out;
}

/**
 * `user-card` -> `UserCard`, `people-_name` -> `PeopleName`, `404` -> `_404`.
 *
 * The result has to be a valid TypeScript identifier, and a route named for a
 * status code starts with a digit, which is a syntax error, not a style one.
 *
 * @param {string} name a tag or a route id
 * @returns {string} PascalCase, safe as a type name
 */
export function interfaceName(name) {
  const camel = String(name)
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');

  if (!camel) return 'Anonymous';
  return /^[0-9]/.test(camel) ? `_${camel}` : camel;
}
