// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

/** Properties of `<person-card>`, from its <script properties> block. */
export type PersonCardProps = {
  name: string;
  role: string;
  tags: any[];
};

/** Properties of `<site-note>`, from its <script properties> block. */
export type SiteNoteProps = {
  tone: string;
  label: string;
};

/** Properties of `<tally-box>`, from its <script properties> block. */
export type TallyBoxProps = {
  label: string;
};

/** Internal state of `<tally-box>`, from its <script state> block. */
export type TallyBoxState = {
  n: number;
};

/** Members of `<tally-box>`, from its `export const prototype`. */
export type TallyBoxMembers = {
  bump(by?: number): void;
};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {
  people: {
    slug: string;
    name: string;
    role: string;
    tags: string[];
  }[];
};

/** The `ctx` argument of `404`'s <script server> loader. */
export type _404Context = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  htmlAttrs: Record<string, string | boolean | null>;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void
};

/** Data returned by `404`'s <script server> block. */
export type _404Data = {};

declare global {
  interface HTMLElementTagNameMap {
    "person-card": HTMLElement;
    "site-note": HTMLElement;
    "tally-box": HTMLElement & TallyBoxProps & TallyBoxState & TallyBoxMembers;
  }
}
